name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t spring-chat-cicd -f ./Dockerfile .
          docker tag spring-chat-cicd chwangmin/spring-chat-cicd:${GITHUB_SHA::7}
          docker push chwangmin/spring-chat-cicd:${GITHUB_SHA::7}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker stop server
            docker pull chwangmin/spring-chat-cicd:${GITHUB_SHA::7}
            docker tag chwangmin/spring-chat-cicd:${GITHUB_SHA::7} spring-chat-cicd
            docker run -d -rm --name server -p 80:8080 spring-chat-cicd